[[redirects]]
  from = "/a/:short_code"
  to = "/.netlify/functions/handle-action?short_code=:short_code"
  status = 200
  force = true

[[redirects]]
  from = "/x/:short_code"
  to = "/.netlify/functions/handle-action?short_code=:short_code"
  status = 200