[build]
  publish = "uat-static"
  functions = "uat-disabled"
  edge_functions = "uat-disabled"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store"
    X-Robots-Tag = "noindex, nofollow"
